# Generated by Django 3.0.7 on 2020-06-25 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Weblog', '0002_auto_20200625_0434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
