# Generated by Django 3.0.7 on 2020-06-25 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Weblog', '0004_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
